# Command-line parameter (must be first for dot sourcing compatibility)
param([string]$InputPath)

# Subtitle translation module
# Supports AI translation and Google Translate

# Dot source dependencies if not already loaded
if (-not (Get-Command "Import-SubtitleFile" -ErrorAction SilentlyContinue)) {
    . "$PSScriptRoot\subtitle-utils.ps1"
}
if (-not (Get-Command "Invoke-AiCompletion" -ErrorAction SilentlyContinue)) {
    . "$PSScriptRoot\ai-client.ps1"
}
if (-not (Get-Command "Invoke-GoogleTranslate" -ErrorAction SilentlyContinue)) {
    . "$PSScriptRoot\google-translate.ps1"
}
if (-not (Get-Command "Get-AllGlossaryTerms" -ErrorAction SilentlyContinue)) {
    . "$PSScriptRoot\glossary.ps1"
}

# Configuration (set by vts.ps1 from config.json)
$script:TranslateMethod = "ai"  # "ai" or "google"
$script:TargetLanguage = "zh-CN"
$script:TranslateOutputDir = "$PSScriptRoot\..\output"

#region Main Translation Function

# Main function: Translate subtitle file
function Invoke-SubtitleTranslator {
    param(
        [Parameter(Mandatory=$true)]
        [string]$InputPath,
        [string]$OutputPath = "",
        [string]$Method = "",
        [string]$TargetLanguage = "",
        [switch]$SkipProofread,
        [switch]$GenerateAss,
        [switch]$Quiet
    )

    if (-not (Test-Path -LiteralPath $InputPath)) {
        throw "Subtitle file not found: $InputPath"
    }

    # Use configured values if not specified
    if (-not $Method) { $Method = $script:TranslateMethod }
    if (-not $TargetLanguage) { $TargetLanguage = $script:TargetLanguage }

    if (-not $Quiet) {
        Write-Host "================================================" -ForegroundColor Cyan
        Write-Host "Subtitle Translator" -ForegroundColor Yellow
        Write-Host "================================================" -ForegroundColor Cyan
        Write-Host "  Method: $Method" -ForegroundColor Gray
        Write-Host "  Target: $TargetLanguage" -ForegroundColor Gray
        Write-Host "================================================" -ForegroundColor Cyan
        Write-Host ""
    }

    # Load subtitle file with auto-generated detection
    if (-not $Quiet) { Write-Host "Loading subtitle file..." -ForegroundColor Cyan }
    $subtitleData = Import-SubtitleFile -Path $InputPath -DetectAutoGenerated

    # Handle auto-generated subtitles with word-level timestamps
    if ($subtitleData.IsAutoGenerated) {
        if (-not $Quiet) {
            Write-Host "Detected auto-generated subtitle with word-level timestamps" -ForegroundColor Yellow
            Write-Host "Using AI to segment into proper sentences..." -ForegroundColor Cyan
        }

        # Use AI to segment the continuous text into sentences
        $sentences = Invoke-SentenceSegmentation -FullText $subtitleData.FullText

        # Map sentences back to timestamps using word timing data
        $entries = ConvertTo-SubtitleEntriesFromSentences -Sentences $sentences -Words $subtitleData.Words

        if (-not $Quiet) { Write-Host "Created $($entries.Count) subtitle entries from auto-generated text" -ForegroundColor Green }
    } else {
        $entries = $subtitleData.Entries
    }

    if ($entries.Count -eq 0) {
        throw "No subtitle entries found in file"
    }

    if (-not $Quiet) { Write-Host "Found $($entries.Count) subtitle entries" -ForegroundColor Gray }

    # Check source language
    $langCheck = Test-SubtitleLanguage -Entries $entries -ExpectedLanguage "en"
    if (-not $Quiet) { Write-Host "Detected language: $($langCheck.DetectedLanguage) (confidence: $($langCheck.Confidence))" -ForegroundColor Gray }

    if ($langCheck.DetectedLanguage -eq $TargetLanguage -or
        ($TargetLanguage -match 'zh' -and $langCheck.DetectedLanguage -eq 'zh')) {
        if (-not $Quiet) { Write-Host "Warning: Source language appears to be the same as target language" -ForegroundColor Yellow }
    }

    # Translate based on method
    $bilingualEntries = switch ($Method.ToLower()) {
        'ai' {
            Invoke-AiTranslateFlow -Entries $entries -TargetLanguage $TargetLanguage -SkipProofread:$SkipProofread
        }
        'google' {
            Invoke-GoogleTranslateFlow -Entries $entries -TargetLanguage $TargetLanguage
        }
        default {
            throw "Unknown translation method: $Method"
        }
    }

    # Apply text formatting to translations (Chinese spacing/punctuation)
    if ($TargetLanguage -match 'zh') {
        if (-not $Quiet) { Write-Host "Applying Chinese text formatting..." -ForegroundColor Cyan }
        $bilingualEntries = $bilingualEntries | ForEach-Object {
            $translationText = if ($_.Translation) { Format-ChineseText -Text $_.Translation } else { "" }
            @{
                StartTime = $_.StartTime
                EndTime = $_.EndTime
                Original = $_.Original
                Translation = $translationText
            }
        }
    }

    # Determine output path
    if (-not $OutputPath) {
        if (-not (Test-Path $script:TranslateOutputDir)) {
            New-Item -ItemType Directory -Path $script:TranslateOutputDir -Force | Out-Null
        }

        $file = Get-Item -LiteralPath $InputPath
        $baseName = $file.BaseName

        if ($GenerateAss) {
            $OutputPath = Join-Path $script:TranslateOutputDir "$baseName.bilingual.ass"
        }
        else {
            $OutputPath = Join-Path $script:TranslateOutputDir "$baseName.bilingual.ass"
        }
    }

    # Generate ASS file
    if (-not $Quiet) { Write-Host "Generating bilingual ASS subtitle..." -ForegroundColor Cyan }
    $assContent = New-BilingualAssContent -BilingualEntries $bilingualEntries
    Export-AssFile -Path $OutputPath -Content $assContent

    if (-not $Quiet) {
        Write-Host ""
        Write-Host "Translation complete!" -ForegroundColor Green
        Write-Host "Output: $OutputPath" -ForegroundColor Gray
    }

    return @{
        OutputPath = $OutputPath
        EntryCount = $bilingualEntries.Count
        Method = $Method
    }
}

#endregion

#region AI Translation Flow

function Invoke-AiTranslateFlow {
    param(
        [Parameter(Mandatory=$true)]
        [array]$Entries,
        [string]$TargetLanguage = "Chinese (Simplified)",
        [switch]$SkipProofread
    )

    # Check AI configuration
    if (-not $script:AiClient_ApiKey) {
        throw "AI API key not configured. Please set up in Settings."
    }

    # Load glossary
    Write-Host "Loading glossaries..." -ForegroundColor Cyan
    $glossary = Get-AllGlossaryTerms
    Write-Host "  Loaded $($glossary.Count) terms" -ForegroundColor Gray

    # Optionally run AI segmentation for better sentence boundaries
    # (Skip for now as original timing is usually acceptable)

    # Translate with AI
    Write-Host "Translating with AI ($($script:AiClient_Model))..." -ForegroundColor Cyan

    # Convert target language code to full name for AI
    $targetLangName = switch ($TargetLanguage) {
        'zh-CN' { 'Chinese (Simplified)' }
        'zh-TW' { 'Chinese (Traditional)' }
        'ja' { 'Japanese' }
        'ko' { 'Korean' }
        default { $TargetLanguage }
    }

    $bilingualEntries = Invoke-SubtitleTranslate -Entries $Entries -TargetLanguage $targetLangName -Glossary $glossary

    # Run global proofreading
    if (-not $SkipProofread) {
        Write-Host "Running AI proofreading..." -ForegroundColor Cyan
        $bilingualEntries = Invoke-GlobalProofread -BilingualEntries $bilingualEntries -TargetLanguage $targetLangName
    }

    return $bilingualEntries
}

#endregion

#region Google Translation Flow

function Invoke-GoogleTranslateFlow {
    param(
        [Parameter(Mandatory=$true)]
        [array]$Entries,
        [string]$TargetLanguage = "zh-CN"
    )

    Write-Host "Translating with Google Translate..." -ForegroundColor Cyan

    # Get language code
    $targetCode = Get-GoogleLanguageCode -LanguageName $TargetLanguage

    # Use sentence-based translation for better quality
    $bilingualEntries = Invoke-GoogleSentenceTranslate -Entries $Entries -TargetLanguage $targetCode

    return $bilingualEntries
}

#endregion

#region Project Integration

# Translate subtitle and save to project folder
function Invoke-ProjectSubtitleTranslator {
    param(
        [Parameter(Mandatory=$true)]
        [string]$SubtitlePath,
        [Parameter(Mandatory=$true)]
        [string]$ProjectDir,
        [string]$Method = "",
        [string]$TargetLanguage = ""
    )

    if (-not (Test-Path -LiteralPath $SubtitlePath)) {
        throw "Subtitle file not found: $SubtitlePath"
    }

    if (-not (Test-Path -LiteralPath $ProjectDir)) {
        throw "Project directory not found: $ProjectDir"
    }

    $outputPath = Join-Path $ProjectDir "bilingual.ass"

    $result = Invoke-SubtitleTranslator -InputPath $SubtitlePath -OutputPath $outputPath -Method $Method -TargetLanguage $TargetLanguage

    return $result
}

#endregion

#region Command-line Interface

if ($InputPath) {
    try {
        $result = Invoke-SubtitleTranslator -InputPath $InputPath
        Write-Host ""
        Write-Host "Success!" -ForegroundColor Green
    }
    catch {
        Write-Host "Error: $_" -ForegroundColor Red
        exit 1
    }
}
elseif ($MyInvocation.InvocationName -ne '.') {
    Write-Host "Usage: translate.bat <subtitle_file>" -ForegroundColor Yellow
    Write-Host "Translates subtitle file and generates bilingual ASS" -ForegroundColor Gray
    Write-Host ""
    Write-Host "Examples:" -ForegroundColor Gray
    Write-Host "  translate.bat video.en.vtt" -ForegroundColor Gray
    Write-Host "  translate.bat subtitles.srt" -ForegroundColor Gray
    exit 1
}

#endregion
